# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - Revolute 2
      - Revolute 6
      - Revolute 7
      - Revolute 8
      - Revolute 9
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - Revolute 27
      - Revolute 31
    action_ns: gripper_cmd
    default: true